// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import (
	auth "github.com/Kenplix/url-shrtnr/pkg/auth"
	mock "github.com/stretchr/testify/mock"
)

// TokensService is an autogenerated mock type for the TokensService type
type TokensService struct {
	mock.Mock
}

// CreateTokens provides a mock function with given fields: id
func (_m *TokensService) CreateTokens(id string) (auth.Tokens, error) {
	ret := _m.Called(id)

	var r0 auth.Tokens
	if rf, ok := ret.Get(0).(func(string) auth.Tokens); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(auth.Tokens)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ParseAccessToken provides a mock function with given fields: token
func (_m *TokensService) ParseAccessToken(token string) (string, error) {
	ret := _m.Called(token)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ParseRefreshToken provides a mock function with given fields: token
func (_m *TokensService) ParseRefreshToken(token string) (string, error) {
	ret := _m.Called(token)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewTokensService interface {
	mock.TestingT
	Cleanup(func())
}

// NewTokensService creates a new instance of TokensService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTokensService(t mockConstructorTestingTNewTokensService) *TokensService {
	mock := &TokensService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
