// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	usecase "github.com/Kenplix/url-shrtnr/internal/usecase"
)

// UsersService is an autogenerated mock type for the UsersService type
type UsersService struct {
	mock.Mock
}

// SignIn provides a mock function with given fields: ctx, input
func (_m *UsersService) SignIn(ctx context.Context, input usecase.UserSignInInput) (usecase.Tokens, error) {
	ret := _m.Called(ctx, input)

	var r0 usecase.Tokens
	if rf, ok := ret.Get(0).(func(context.Context, usecase.UserSignInInput) usecase.Tokens); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(usecase.Tokens)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, usecase.UserSignInInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SignUp provides a mock function with given fields: ctx, input
func (_m *UsersService) SignUp(ctx context.Context, input usecase.UserSignUpInput) error {
	ret := _m.Called(ctx, input)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.UserSignUpInput) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewUsersService interface {
	mock.TestingT
	Cleanup(func())
}

// NewUsersService creates a new instance of UsersService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUsersService(t mockConstructorTestingTNewUsersService) *UsersService {
	mock := &UsersService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
