// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/kenplix/url-shrtnr/internal/entity"
	mock "github.com/stretchr/testify/mock"

	primitive "go.mongodb.org/mongo-driver/bson/primitive"

	service "github.com/kenplix/url-shrtnr/internal/service"
)

// AuthService is an autogenerated mock type for the AuthService type
type AuthService struct {
	mock.Mock
}

// SignIn provides a mock function with given fields: ctx, schema
func (_m *AuthService) SignIn(ctx context.Context, schema service.UserSignInSchema) (entity.Tokens, error) {
	ret := _m.Called(ctx, schema)

	var r0 entity.Tokens
	if rf, ok := ret.Get(0).(func(context.Context, service.UserSignInSchema) entity.Tokens); ok {
		r0 = rf(ctx, schema)
	} else {
		r0 = ret.Get(0).(entity.Tokens)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, service.UserSignInSchema) error); ok {
		r1 = rf(ctx, schema)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SignOut provides a mock function with given fields: ctx, userID
func (_m *AuthService) SignOut(ctx context.Context, userID primitive.ObjectID) error {
	ret := _m.Called(ctx, userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SignUp provides a mock function with given fields: ctx, schema
func (_m *AuthService) SignUp(ctx context.Context, schema service.UserSignUpSchema) error {
	ret := _m.Called(ctx, schema)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, service.UserSignUpSchema) error); ok {
		r0 = rf(ctx, schema)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewAuthService interface {
	mock.TestingT
	Cleanup(func())
}

// NewAuthService creates a new instance of AuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAuthService(t mockConstructorTestingTNewAuthService) *AuthService {
	mock := &AuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
