http:
  port: 80
  readTimeout: 5s
  writeTimeout: 5s
  shutdownTimeout: 3s

database:
  use: mongodb

logger:
  level: debug

hasher:
  use: argon2
  bcrypt:
    cost: 6
  argon2:
    memory: 65536 # 64 * 1024
    iterations: 4
    parallelism: 2
    saltLength: 16
    keyLength: 16

authorization:
  accessTokenTTL: 15m
  refreshTokenTTL: 1h
