http:
  port: 8080
  readTimeout: 5s
  writeTimeout: 5s
  shutdownTimeout: 3s

database:
  use: mongodb

logger:
  level: info

hasher:
  use: bcrypt
  bcrypt:
    cost: 16
  argon2:
    memory: 65536 # 64 * 1024
    iterations: 6
    parallelism: 4
    saltLength: 16
    keyLength: 16

jwt:
  accessToken:
    ttl: 2h
  refreshToken:
    ttl: 720h
  inactiveTimeout: 1h
