basePath: /api/v1
host: localhost:80
info:
  contact:
    email: tolstoi.job@gmail.com
    name: Oleksandr Tolstoi
  description: REST API for URL shortener app
  title: URL shortener API
  version: "1.1"
paths: {}
securityDefinitions:
  JWT-RS256:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
